/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-12-09 at 08:48:39 UTC 
 * Modify at your own risk.
 */

package com.appspot.ruby_mine.rubymine.model;

/**
 * Model definition for Coupon.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the rubymine. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Coupon extends com.google.api.client.json.GenericJson {
	public static final int STATE_UNUSED = 0;
	public static final int STATE_EXPIRED = 1;
	public static final int STATE_USED = 2;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String desc;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long expirationDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long gemId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String imageKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer resultCode;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String rubymineName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer state;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long userId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDesc() {
    return desc;
  }

  /**
   * @param desc desc or {@code null} for none
   */
  public Coupon setDesc(java.lang.String desc) {
    this.desc = desc;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getExpirationDate() {
    return expirationDate;
  }

  /**
   * @param expirationDate expirationDate or {@code null} for none
   */
  public Coupon setExpirationDate(java.lang.Long expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getGemId() {
    return gemId;
  }

  /**
   * @param gemId gemId or {@code null} for none
   */
  public Coupon setGemId(java.lang.Long gemId) {
    this.gemId = gemId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Coupon setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getImageKey() {
    return imageKey;
  }

  /**
   * @param imageKey imageKey or {@code null} for none
   */
  public Coupon setImageKey(java.lang.String imageKey) {
    this.imageKey = imageKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public Coupon setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getResultCode() {
    return resultCode;
  }

  /**
   * @param resultCode resultCode or {@code null} for none
   */
  public Coupon setResultCode(java.lang.Integer resultCode) {
    this.resultCode = resultCode;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRubymineName() {
    return rubymineName;
  }

  /**
   * @param rubymineName rubymineName or {@code null} for none
   */
  public Coupon setRubymineName(java.lang.String rubymineName) {
    this.rubymineName = rubymineName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getState() {
    return state;
  }

  /**
   * @param state state or {@code null} for none
   */
  public Coupon setState(java.lang.Integer state) {
    this.state = state;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public Coupon setUserId(java.lang.Long userId) {
    this.userId = userId;
    return this;
  }

  @Override
  public Coupon set(String fieldName, Object value) {
    return (Coupon) super.set(fieldName, value);
  }

  @Override
  public Coupon clone() {
    return (Coupon) super.clone();
  }

}
