/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-12-09 at 08:48:39 UTC 
 * Modify at your own risk.
 */

package com.appspot.ruby_mine.rubymine.model;

/**
 * Model definition for RubyCol.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the rubymine. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class RubyCol extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Rubymine> givers;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Rubymine planter;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer resultCode;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Ruby> rubies;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Rubymine> getGivers() {
    return givers;
  }

  /**
   * @param givers givers or {@code null} for none
   */
  public RubyCol setGivers(java.util.List<Rubymine> givers) {
    this.givers = givers;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Rubymine getPlanter() {
    return planter;
  }

  /**
   * @param planter planter or {@code null} for none
   */
  public RubyCol setPlanter(Rubymine planter) {
    this.planter = planter;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getResultCode() {
    return resultCode;
  }

  /**
   * @param resultCode resultCode or {@code null} for none
   */
  public RubyCol setResultCode(java.lang.Integer resultCode) {
    this.resultCode = resultCode;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Ruby> getRubies() {
    return rubies;
  }

  /**
   * @param rubies rubies or {@code null} for none
   */
  public RubyCol setRubies(java.util.List<Ruby> rubies) {
    this.rubies = rubies;
    return this;
  }

  @Override
  public RubyCol set(String fieldName, Object value) {
    return (RubyCol) super.set(fieldName, value);
  }

  @Override
  public RubyCol clone() {
    return (RubyCol) super.clone();
  }

}
