/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-12-09 at 08:48:39 UTC 
 * Modify at your own risk.
 */

package com.appspot.ruby_mine.rubymine.model;

/**
 * Model definition for Userpair.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the rubymine. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Userpair extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer resultCode;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer state;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long userIdA;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long userIdB;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userImageKeyA;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userImageKeyB;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userNameA;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userNameB;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Userpair setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getResultCode() {
    return resultCode;
  }

  /**
   * @param resultCode resultCode or {@code null} for none
   */
  public Userpair setResultCode(java.lang.Integer resultCode) {
    this.resultCode = resultCode;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getState() {
    return state;
  }

  /**
   * @param state state or {@code null} for none
   */
  public Userpair setState(java.lang.Integer state) {
    this.state = state;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserIdA() {
    return userIdA;
  }

  /**
   * @param userIdA userIdA or {@code null} for none
   */
  public Userpair setUserIdA(java.lang.Long userIdA) {
    this.userIdA = userIdA;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserIdB() {
    return userIdB;
  }

  /**
   * @param userIdB userIdB or {@code null} for none
   */
  public Userpair setUserIdB(java.lang.Long userIdB) {
    this.userIdB = userIdB;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserImageKeyA() {
    return userImageKeyA;
  }

  /**
   * @param userImageKeyA userImageKeyA or {@code null} for none
   */
  public Userpair setUserImageKeyA(java.lang.String userImageKeyA) {
    this.userImageKeyA = userImageKeyA;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserImageKeyB() {
    return userImageKeyB;
  }

  /**
   * @param userImageKeyB userImageKeyB or {@code null} for none
   */
  public Userpair setUserImageKeyB(java.lang.String userImageKeyB) {
    this.userImageKeyB = userImageKeyB;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserNameA() {
    return userNameA;
  }

  /**
   * @param userNameA userNameA or {@code null} for none
   */
  public Userpair setUserNameA(java.lang.String userNameA) {
    this.userNameA = userNameA;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserNameB() {
    return userNameB;
  }

  /**
   * @param userNameB userNameB or {@code null} for none
   */
  public Userpair setUserNameB(java.lang.String userNameB) {
    this.userNameB = userNameB;
    return this;
  }

  @Override
  public Userpair set(String fieldName, Object value) {
    return (Userpair) super.set(fieldName, value);
  }

  @Override
  public Userpair clone() {
    return (Userpair) super.clone();
  }

}
